[project]
name = "LuxeChain"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = "/home/runner/LuxeChain/LuxeChain/LuxeChain/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.authentication]
path = "contracts/authentication.clar"

[contracts.fashion-item]
path = "contracts/fashion-item.clar"

[contracts.luxury-auth]
path = "contracts/luxury-auth.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
